services:
  minio:
    image: minio/minio:latest
    container_name: classicmodels-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: https://minio-api.data-engineering-lab1.fratellidevs.com
      MINIO_BROWSER_REDIRECT_URL: https://minio-console.data-engineering-lab1.fratellidevs.com
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 10

  create-bucket:
    image: minio/mc:latest
    container_name: classicmodels-minio-create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing local/classicmodels;
      mc anonymous set none local/classicmodels;
      exit 0;
      "

volumes:
  minio-data:
